# Generated by Django 6.0 on 2026-01-05 16:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(blank=True, default='Неизвестный автор', max_length=100, verbose_name='Автор')),
                ('publication_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)], verbose_name='Год издания')),
                ('genre', models.CharField(choices=[('fiction', 'Художественная литература'), ('fantasy', 'Фэнтези'), ('scifi', 'Научная фантастика'), ('detective', 'Детектив'), ('romance', 'Роман'), ('biography', 'Биография'), ('history', 'История'), ('science', 'Наука'), ('self_help', 'Саморазвитие'), ('other', 'Другое')], default='fiction', max_length=50, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Обложка')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_status', models.CharField(choices=[('not_started', 'Не начата'), ('reading', 'Читаю'), ('finished', 'Прочитана'), ('abandoned', 'Брошена'), ('planned', 'В планах')], default='not_started', max_length=20, verbose_name='Статус чтения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
